---
name: Generate Talos image

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Target repository name"
        default: ${{ github.repository }}
        required: false
        type: string
      renovateLogLevel:
        description: "Log-Level"
        default: "debug"
        required: false
        type: string
      configurationFile:
        description: "Renovate configuration file"
        default: ".github/renovate.json5"
        required: false
        type: string

jobs:
  check-release:
    name: Check talos release version
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest Talos release information
        id: talos-release
        run: |
          talos_release_json=$(curl -sL https://api.github.com/repos/siderolabs/talos/releases/latest)
          talos_release_tag=
          talos_release_body=
          echo "talos_release_tag=$talos_release_tag" >> $GITHUB_OUTPUT
          echo "talos_release_body=$talos_release_body" >> $GITHUB_OUTPUT
