---
name: Generate Talos image

on:
  workflow_call:
    inputs:
      talosVersion:
        description: "Talos release version"
        required: true
        type: string
      talosExtensionsImage:
        description: "Talos extensions"
        required: true
        type: string
      arch:
        description: "Build architecture"
        required: true
        type: string

jobs:
  build-talos-assets:
    name: Build talos images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/siderolabs/imager:${{ inputs.talosVersion }}
      options: --privileged
      volumes:
        - /dev:/dev
    steps:
      - name: Build ${{ inputs.arch }} installer
        run: |
          /bin/imager installer \
            --arch ${{ inputs.arch }} \
            ${{ inputs.talosExtensionsImage }}

      - name: Build ${{ inputs.arch }} metal
        run: |
          /bin/imager metal \
            --arch ${{ inputs.arch }} \
            --extra-kernel-arg net.ifnames=0 \
            ${{ inputs.talosExtensionsImage }}

      - name: Build ${{ inputs.arch }} iso
        run: |
          /bin/imager iso \
            --arch ${{ inputs.arch }} \
            --extra-kernel-arg net.ifnames=0 \
            ${{ inputs.talosExtensionsImage }}

      - name: Upload ${{ inputs.arch }} installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: talos-installer-${{ inputs.arch }}
          path: /out/installer-${{ inputs.arch }}.tar
          if-no-files-found: error
          retention-days: 1

      - name: Upload ${{ inputs.arch }} metal artifact
        uses: actions/upload-artifact@v4
        with:
          name: talos-images-${{ inputs.arch }}
          path: |
            /out/metal-${{ inputs.arch }}.raw.xz
            /out/metal-${{ inputs.arch }}.iso
          if-no-files-found: error
          retention-days: 1
