---
name: Generate Talos image

on:
  workflow_call:
    inputs:
      talosVersion:
        description: "Talos release version"
        required: true
        type: string
      talosExtensionsImage:
        description: "Talos extensions"
        required: true
        type: string

jobs:
  build-talos-assets:
    name: Build talos images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/siderolabs/imager:${{ inputs.talosVersion }}
      options: --privileged
      volumes:
        - /dev:/dev
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Build ${{ matrix.arch }} installer
        run: |
          /bin/imager installer \
            --arch ${{ matrix.arch }} \
            ${{ inputs.talosExtensionsImage }}

      - name: Build ${{ matrix.arch }} metal
        run: |
          /bin/imager metal \
            --arch ${{ matrix.arch }} \
            --extra-kernel-arg net.ifnames=0 \
            ${{ inputs.talosExtensionsImage }}

      - name: Upload ${{ matrix.arch }} installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: installer-${{ matrix.arch }}
          path: /out/metal-${{ matrix.arch }}-installer.tar
          if-no-files-found: error
          retention-days: 1

      - name: Upload ${{ matrix.arch }} metal artifact
        uses: actions/upload-artifact@v3
        with:
          name: talos-${{ matrix.arch }}
          path: /out/metal-${{ matrix.arch }}.raw.xz
          if-no-files-found: error
          retention-days: 1
