---
name: Check Talos release

on:
  workflow_call:
    inputs:
      repositoryName:
        description: "Target repository name"
        required: true
        type: string
    outputs:
      newTalosReleaseFound:
        value: ${{ jobs.check-release.outputs.newTalosReleaseFound }}
      talosReleaseTag:
        value: ${{ jobs.check-release.outputs.talosReleaseTag }}
      talosReleaseBody:
        value: ${{ jobs.check-release.outputs.talosReleaseBody }}

jobs:
  check-release:
    name: Check talos release version
    runs-on: ubuntu-latest
    outputs:
      newTalosReleaseFound: "${{ steps.talos-release.outputs.talos_release_tag != steps.repository-release.outputs.repository_release_tag }}"
      talosReleaseTag: ${{ steps.talos-release.outputs.talos_release_tag }}
      talosReleaseBody: ${{ steps.talos-release.outputs.talos_release_body }}
    steps:
      - name: Fetch latest Talos release information
        id: talos-release
        run: |
          talos_release_json=$(curl -sL https://api.github.com/repos/siderolabs/talos/releases/latest)
          echo "talos_release_tag=$(echo "$talos_release_json" | jq -r ".tag_name")" >> $GITHUB_OUTPUT
          {
            echo 'talos_release_body<<EOF'
            echo "$talos_release_json" | jq -r ".body"
            echo EOF
          } >> $GITHUB_OUTPUT
          echo $(echo "$talos_release_json" | jq -r ".tag_name")
      - name: Fetch latest repository release version
        id: repository-release
        run: |
          repository_release_tag=$(curl -sL https://api.github.com/repos/${{ inputs.repositoryName }}/releases/latest | jq -r ".tag_name")
          echo "repository_release_tag=$repository_release_tag" >> $GITHUB_OUTPUT
          echo $repository_release_tag
